### ISSUE TITLE
Player stays parented to moving platform after jumping off

### ISSUE THREAD

**Issue by approboGames** [britzl/platypus#5]
Can be replicated using HTML5 demo on github page.

When player jumps off a moving platform, the player object is still parented to the platform until it collides with another object. This causes the player to move in relation to the platform in mid air.

Can be tested by standing on a moving platform and simply jumping without moving. Player will follow platforms movement.

**Comment by britzl** [comment]
The HTML5 demo was not updated to the latest release of Platypus (3.0.2). There's been a number of improvements since the demo was built, with ground detection and parenting being one of them. Please try the latest version of Platypus and the new demo and reopen this issue if you've found a way to reproduce the issue.

**Comment by approboGames** [comment]
Can confirm this is working as expected in 3.0.2. Thanks
